### ISSUE TITLE
[ZLC] FAV Data

### ISSUE THREAD

**Issue by KSanders7070** [vFlightDataSystems/VATSIM_TDLS_backend#4]
Please include the following data into the vEDST database, when able.
[ZLC_APP_FAV_Data.txt](https://github.com/CaptainTux/VATSIM_TDLS_backend/files/8064639/ZLC_APP_FAV_Data.txt)
[ZLC_CTR_FAV_Data.txt](https://github.com/CaptainTux/VATSIM_TDLS_backend/files/8064640/ZLC_CTR_FAV_Data.txt)

**Comment by CaptainTux** [comment]
Done
